// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXC2rwVtCXBwG4eMNWwxoWoAI57823keQ',
    appId: '1:822197568314:web:6508afb11043b0a1464603',
    messagingSenderId: '822197568314',
    projectId: 'elrace-578e7',
    authDomain: 'elrace-578e7.firebaseapp.com',
    storageBucket: 'elrace-578e7.firebasestorage.app',
    measurementId: 'G-1R1NX6C83H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYyh1LsubgOP-iUdR6aPtZkWrMjMZjqVc',
    appId: '1:392748487890:android:c475c90ac7c1dcf00f490b',
    messagingSenderId: '392748487890',
    projectId: 'elrace-new',
    storageBucket: 'elrace-new.firebasestorage.app',
    databaseURL: 'https://elrace-new-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt_EnbWPKn-BDXOLXSdIACvlLTEAk_k2k',
    appId: '1:822197568314:ios:6fd830ee9a8a91e6464603',
    messagingSenderId: '822197568314',
    projectId: 'elrace-578e7',
    storageBucket: 'elrace-578e7.firebasestorage.app',
    iosBundleId: 'com.elRace.elRace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt_EnbWPKn-BDXOLXSdIACvlLTEAk_k2k',
    appId: '1:822197568314:ios:6fd830ee9a8a91e6464603',
    messagingSenderId: '822197568314',
    projectId: 'elrace-578e7',
    storageBucket: 'elrace-578e7.firebasestorage.app',
    iosBundleId: 'com.elRace.elRace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXC2rwVtCXBwG4eMNWwxoWoAI57823keQ',
    appId: '1:822197568314:web:78499566cde986b9464603',
    messagingSenderId: '822197568314',
    projectId: 'elrace-578e7',
    authDomain: 'elrace-578e7.firebaseapp.com',
    storageBucket: 'elrace-578e7.firebasestorage.app',
    measurementId: 'G-JDQEFRGN8M',
  );

}